spring.application.name=rentacar

spring.datasource.url= jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username= ${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Exponer el endpoint específico de prometheus a través de la web
management.endpoints.web.exposure.include=prometheus,health,info
# Ruta base del actuator (por defecto: /actuator)
management.endpoints.web.base-path=/actuator
# Añadir etiquetas comunes a todas las métricas
management.metrics.tags.application=${spring.application.name}


# 2. Muestreo al 100% (para que trace absolutamente todas las peticiones en la clase)
management.tracing.sampling.probability=1.0
# 3. Dirección de Tempo (El puerto 4318 que levantamos en el Docker Compose)
management.otlp.tracing.endpoint=http://tempo:4318/v1/traces
# 4. El formato del LOG (La clave de la correlación)
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

management.tracing.propagation.type=W3C