apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-app
        # La imagen se reemplazará dinámicamente en el pipeline de GitHub Actions
        image: 323260690734.dkr.ecr.us-east-1.amazonaws.com/back_2:${IMAGE_TAG}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80       # Puerto expuesto al mundo (Load Balancer)
      targetPort: 8080 # Puerto donde corre la app dentro del contenedor